set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -ag terminal-overrides ',*:Ss=\E[%p1%d q:Se=\E[2 q'
set -g allow-passthrough on

set -g prefix C-a
set -g mouse on
set -g base-index 1              # start indexing windows at 1 instead of 0
set -g detach-on-destroy off     # don't exit from tmux when closing a session
set -g escape-time 0             # zero-out escape time delay
set -g history-limit 1000000     # increase history size (from 2,000)
set -g renumber-windows on       # renumber all windows when any window is closed
set -g set-clipboard on          # use system clipboard
set -g wrap-search off           # Don't wrap search in tmux

setw -g mode-keys vi

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# pane resizing
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Move window to the right or left
bind-key -r < swap-window -t -1\; select-window -t -1
bind-key -r > swap-window -t +1\; select-window -t +1

bind s split-window -v -c "#{pane_current_path}"
bind v split-window -h -b -c "#{pane_current_path}"

bind c new-window -c "#{pane_current_path}"

#Keep pressing key (without prefix) → continues cycling through windows
bind-key -r n next-window
bind-key -r p previous-window

bind Enter copy-mode # enter copy mode
#vim-like behavior (v to select, y to yank).
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel

# configure how window list is shown at choose-tree
bind T choose-tree -w -F " #{=/-32/...:#{s|$USER|~|:#{b:pane_current_path}}} ->  #{pane_current_command}"
# bind-key T run-shell "sesh window \"$(sesh window | fzf-tmux -p 60%,50% --prompt '󱇛  ')\""
bind-key w run-shell "sesh connect \"$(
  sesh list --icons | fzf-tmux -p 80%,70% \
    --no-sort --ansi --border-label ' sesh ' --prompt '    ' \
    --header '  ^a all ^t tmux ^g configs ^x zoxide ^d tmux kill ^f find' \
    --bind 'tab:down,btab:up' \
    --bind 'ctrl-a:change-prompt(  )+reload(sesh list --icons)' \
    --bind 'ctrl-t:change-prompt(󱇛  )+reload(sesh list -t --icons)' \
    --bind 'ctrl-g:change-prompt(  )+reload(sesh list -c --icons)' \
    --bind 'ctrl-x:change-prompt(  )+reload(sesh list -z --icons)' \
    --bind 'ctrl-f:change-prompt(  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
    --bind 'ctrl-d:execute(tmux kill-session -t {2..})+change-prompt(   )+reload(sesh list --icons)' \
    --preview-window 'right:55%' \
    --preview 'sesh preview {}'
)\""
bind -N "last-session (via sesh) " W run-shell "sesh last"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'wfxr/tmux-fzf-url'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'rose-pine/tmux'

# Configure Rosé Pine
set -g @rose_pine_variant 'main' # options: main, moon, dawn
set -g @rose_pine_bar_bg_disable 'on'
set -g @rose_pine_bar_bg_disabled_color_option 'default'
set -g @rose_pine_directory 'on'
set -g @rose_pine_disable_active_window_menu 'on'
set -g @rose_pine_only_windows 'off'
set -g @rose_pine_window_status_separator " #[bg=#191724,fg=#26233a,none]│ "
set -g @rose_pine_session_icon ''

# Keep status bar at the top
set -g status-position top
set -g status-justify "absolute-centre"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'

# Keep a blank second status line as bottom padding
set -g status 2
set -g status-format[1] ""
