# Created by Zap installer
[ -f "${XDG_DATA_HOME:-$HOME/.local/share}/zap/zap.zsh" ] && source "${XDG_DATA_HOME:-$HOME/.local/share}/zap/zap.zsh"

plug "$HOME/.config/zsh/aliases.zsh"
plug "$HOME/.config/zsh/exports.zsh"

plug "zsh-users/zsh-autosuggestions"
plug "zap-zsh/supercharge"
plug "zsh-users/zsh-syntax-highlighting"
plug "wintermi/zsh-starship"
plug "zap-zsh/exa"
plug "olets/zsh-abbr"
plug "zsh-users/zsh-history-substring-search"
plug "jeffreytse/zsh-vi-mode"
plug "agkozak/zsh-z"

# Load and initialise completion system
autoload -Uz compinit
compinit

if command -v direnv &> /dev/null; then
  eval "$(direnv hook zsh)"
fi
